### ISSUE TITLE
[EPIC] Add support for other chains when generating the test suite

### ISSUE THREAD

**Issue by srdtrk** [srdtrk/go-codegen#52]
## Description

Currently, the testsuite only comes with wasmd v0.50.0. I'd like the interactive menu to allow users to select the chain's they'd like to use. I'll list the chains that should be supported:

- [ ] wasmd v0.51.0
- [ ] osmosis
- [ ] ibc-go simd v8.3
- [ ] gaia (Cosmos Hub)

And there are some other additional tasks that need to be completed:

- [ ] Add an interactive prompt to enable chain selection by the user.
